# Generated by Django 4.2.30 on 2026-04-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        ('bookings', '0003_scheduledsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_goals', to='tutors.subject')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_goals', to='tutors.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('note', models.TextField()),
                ('homework', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='bookings.scheduledsession')),
                ('student_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='tutors.tutorprofile')),
            ],
        ),
    ]
